#!/bin/sh

# Show USAGE if -h or --help
if [ "${1}" = "-h" ] || [ "${1}" = "--help" ] ; then echo -e "\nUSAGE:\nTo run on localhost: $(basename ${0})\nTo run on <hostname>: $(basename ${0}) <hostname>\n\n" ; exit ; fi

# Make sure we have jtree installed
if ! $(python -c "import jtree") ; then echo -e "\njtree doesn't appear to be installed.  Please install with \"python -m pip install jtree\" and rerun factstree" ; exit ; fi

# If a hostname isn't passed as an arguement, then use localhost
TARGETHOST=localhost ; [[ "${1}" ]] && TARGETHOST="${1}"

# Set the temp directory name for the facts
FACTSDIR="/tmp/factstree.$(date +"%s").tmp"

# Make the FACTSDIR directory
mkdir -p ${FACTSDIR}

# Let the user know we are gathering facts
echo -e "\nProceeding to gather facts for ${TARGETHOST}.  Please be patient....\n"

# Get the facts using the setup module and write them to ${FACTSDIR}/${TARGETHOST} using -t while supressing output to console
ansible ${TARGETHOST} -m setup -t ${FACTSDIR} > /dev/null

# Display the facts in jtree
jtree ${FACTSDIR}/${TARGETHOST}

# Remove ${FACTSDIR}
rm -rf ${FACTSDIR}
