#!/bin/sh

# Make sure we have jtree installed
if ! $(python -c "import jtree") ; then echo -e "\njtree doesn't appear to be installed.  Please install with \"python -m pip install jtree\" and rerun factstree\n\n" ; exit ; fi

# If a hostname isn't passed as an arguement, then use localhost
TARGETHOST=localhost ; [[ "${1}" ]] && TARGETHOST="${1}"

# Set the temp file name for the facts
FACTSFILE="/tmp/factstree.$(date +"%s").tmp"

# Get the facts, clean it up, and write it to the temp file
# Use ansible.builtin.setup as a module and run it against ${TARGETHOST}
# Remove the top two lines which contain ansible return information that hinders json parsing
# Add the opening { in the json file that was removed in the previous command
# Remove the last three lines of the file which hinder clean json parsing
# Append }} to the end of the file to properly close the json and tie up the previous changes we had to make
ansible ${TARGETHOST} -m ansible.builtin.setup | tail -n +2 | sed '1s/^/{/' | head -n -3 | sed '$a}}' > ${FACTSFILE}

# Display the facts in jtree
jtree ${FACTSFILE}

# Remove the temp file
rm ${FACTSFILE}
